properties:
  resources:
    - resource: PowerToysConfigure
      directives:
        description: Configure PowerToys
      settings:
        AlwaysOnTop:
          Hotkey: "<string>"
          FrameEnabled: "<string>"
          FrameThickness: 17
          FrameColor: "<string>"
          FrameOpacity: 17
          FrameAccentColor: "<string>"
          SoundEnabled: "<string>"
          DoNotActivateOnGameMode: "<string>"
          ExcludedApps: "<string>"
          RoundCornersEnabled: "<string>"

        Awake:
          KeepDisplayOn: true
          Mode: TIMED
          IntervalHours: 204
          IntervalMinutes: 211
          ExpirationDateTime: "<string>"

        ColorPicker:
          ActivationShortcut: "<string>"
          CopiedColorRepresentation: "<string>"
          ActivationAction: OpenEditor
          ShowColorName: true

        CropAndLock:
          ReparentHotkey: "<string>"
          ThumbnailHotkey: "<string>"

        EnvironmentVariables:
          LaunchAdministrator: false

        FancyZones:
          FancyzonesShiftDrag: "<string>"
          FancyzonesMouseSwitch: "<string>"
          FancyzonesMouseMiddleClickSpanningMultipleZones: "<string>"
          FancyzonesOverrideSnapHotkeys: "<string>"
          FancyzonesMoveWindowsAcrossMonitors: "<string>"
          FancyzonesMoveWindowsBasedOnPosition: "<string>"
          FancyzonesOverlappingZonesAlgorithm: 129
          FancyzonesDisplayOrWorkAreaChangeMoveWindows: "<string>"
          FancyzonesZoneSetChangeMoveWindows: "<string>"
          FancyzonesAppLastZoneMoveWindows: "<string>"
          FancyzonesOpenWindowOnActiveMonitor: "<string>"
          FancyzonesRestoreSize: "<string>"
          FancyzonesQuickLayoutSwitch: "<string>"
          FancyzonesFlashZonesOnQuickSwitch: "<string>"
          UseCursorposEditorStartupscreen: "<string>"
          FancyzonesShowOnAllMonitors: "<string>"
          FancyzonesSpanZonesAcrossMonitors: "<string>"
          FancyzonesMakeDraggedWindowTransparent: "<string>"
          FancyzonesAllowChildWindowSnap: "<string>"
          FancyzonesDisableRoundCornersOnSnap: "<string>"
          FancyzonesZoneHighlightColor: "<string>"
          FancyzonesHighlightOpacity: 58
          FancyzonesEditorHotkey: "<string>"
          FancyzonesWindowSwitching: "<string>"
          FancyzonesNextTabHotkey: "<string>"
          FancyzonesPrevTabHotkey: "<string>"
          FancyzonesExcludedApps: "<string>"
          FancyzonesBorderColor: "<string>"
          FancyzonesInActiveColor: "<string>"
          FancyzonesNumberColor: "<string>"
          FancyzonesSystemTheme: "<string>"
          FancyzonesShowZoneNumber: "<string>"

        FileLocksmith:
          ExtendedContextMenuOnly: "<string>"

        FindMyMouse:
          ActivationMethod: 99
          ActivationShortcut: "<string>"
          DoNotActivateOnGameMode: "<string>"
          BackgroundColor: "<string>"
          SpotlightColor: "<string>"
          OverlayOpacity: 55
          SpotlightRadius: 5
          AnimationDurationMs: 34
          SpotlightInitialZoom: 189
          ExcludedApps: "<string>"
          ShakingMinimumDistance: 49
          ShakingIntervalMs: 227
          ShakingFactor: 220

        Hosts:
          ShowStartupWarning: false
          LoopbackDuplicates: false
          AdditionalLinesPosition: Bottom
          Encoding: Utf8

        ImageResizer:
          ImageresizerSelectedSizeIndex: 181
          ImageresizerShrinkOnly: "<string>"
          ImageresizerReplace: "<string>"
          ImageresizerIgnoreOrientation: "<string>"
          ImageresizerJpegQualityLevel: 148
          ImageresizerPngInterlaceOption: 158
          ImageresizerTiffCompressOption: 187
          ImageresizerFileName: "<string>"
          ImageresizerKeepDateModified: "<string>"
          ImageresizerFallbackEncoder: "<string>"

        MeasureTool:
          ActivationShortcut: "<string>"
          ContinuousCapture: true
          DrawFeetOnCross: false
          PerColorChannelEdgeDetection: false
          PixelTolerance: 175
          MeasureCrossColor: "<string>"
          DefaultMeasureStyle: 53

        MouseHighlighter:
          ActivationShortcut: "<string>"
          LeftButtonClickColor: "<string>"
          RightButtonClickColor: "<string>"
          AlwaysColor: "<string>"
          HighlightRadius: 132
          HighlightFadeDelayMs: 124
          HighlightFadeDurationMs: 64
          AutoActivate: "<string>"

        MouseJump:
          ActivationShortcut: "<string>"
          ThumbnailSize: "<string>"

        MousePointerCrosshairs:
          ActivationShortcut: "<string>"
          CrosshairsColor: "<string>"
          CrosshairsOpacity: 197
          CrosshairsRadius: 0
          CrosshairsThickness: 123
          CrosshairsBorderColor: "<string>"
          CrosshairsBorderSize: 114
          CrosshairsAutoHide: "<string>"
          CrosshairsIsFixedLengthEnabled: "<string>"
          CrosshairsFixedLength: 124
          AutoActivate: "<string>"

        MouseWithoutBorders:
          ShowOriginalUI: true
          WrapMouse: false
          ShareClipboard: false
          TransferFile: false
          HideMouseAtScreenEdge: true
          DrawMouseCursor: false
          ValidateRemoteMachineIP: false
          SameSubnetOnly: true
          BlockScreenSaverOnOtherMachines: false
          MoveMouseRelatively: true
          BlockMouseAtScreenCorners: true
          ShowClipboardAndNetworkStatusMessages: true
          EasyMouse: 113
          HotKeySwitchMachine: 127
          ToggleEasyMouseShortcut: "<string>"
          LockMachineShortcut: "<string>"
          ReconnectShortcut: "<string>"
          Switch2AllPCShortcut: "<string>"
          DrawMouseEx: false
          Name2IP: "<string>"

        PastePlain:
          ActivationShortcut: "<string>"

        Peek:
          ActivationShortcut: "<string>"
          AlwaysRunNotElevated: "<string>"
          CloseAfterLosingFocus: "<string>"

        PowerAccent:
          ActivationKey: Space
          DoNotActivateOnGameMode: true
          ToolbarPosition: "<string>"
          InputTime: 17
          SelectedLang: "<string>"
          ExcludedApps: "<string>"
          ShowUnicodeDescription: true
          SortByUsageFrequency: false
          StartSelectionFromTheLeft: false

        PowerLauncher:
          OpenPowerLauncher: "<string>"
          IgnoreHotkeysInFullscreen: false
          ClearInputOnLaunch: false
          TabSelectsContextButtons: false
          Theme: HighContrastBlack
          TitleFontSize: 5
          Position: Focus
          UseCentralizedKeyboardHook: true
          SearchQueryResultsWithDelay: true
          SearchInputDelay: 93
          SearchInputDelayFast: 188
          SearchClickedItemWeight: 182
          SearchQueryTuningEnabled: false
          SearchWaitForSlowResults: false
          UsePinyin: true
          GenerateThumbnailsFromFiles: true

        PowerOcr:
          ActivationShortcut: "<string>"
          PreferredLanguage: "<string>"

        PowerPreview:
          EnableSvgPreview: false
          SvgBackgroundColorMode: 19
          SvgBackgroundSolidColor: "<string>"
          SvgBackgroundCheckeredShade: 18
          EnableSvgThumbnail: false
          EnableMdPreview: false
          EnableMonacoPreview: true
          EnableMonacoPreviewWordWrap: true
          MonacoPreviewTryFormat: true
          MonacoPreviewMaxFileSize: 153
          EnablePdfPreview: false
          EnablePdfThumbnail: true
          EnableGcodePreview: false
          EnableGcodeThumbnail: false
          EnableStlThumbnail: true
          StlThumbnailColor: "<string>"
          EnableQoiPreview: false
          EnableQoiThumbnail: true

        PowerRename:
          MRUEnabled: "<string>"
          MaxMRUSize: 141
          ExtendedContextMenuOnly: "<string>"
          UseBoostLib: "<string>"

        RegistryPreview:
          DefaultRegApp: false

        ShortcutGuide:
          OpenShortcutGuide: "<string>"
          OverlayOpacity: 100
          UseLegacyPressWinKeyBehavior: "<string>"
          PressTimeForGlobalWindowsShortcuts: 75
          PressTimeForTaskbarIconShortcuts: 28
          Theme: "<string>"
          DisabledApps: "<string>"

        VideoConference:
          MuteCameraAndMicrophoneHotkey: "<string>"
          MuteMicrophoneHotkey: "<string>"
          PushToTalkMicrophoneHotkey: "<string>"
          PushToReverseEnabled: "<string>"
          MuteCameraHotkey: "<string>"
          SelectedCamera: "<string>"
          SelectedMicrophone: "<string>"
          ToolbarPosition: "<string>"
          ToolbarMonitor: "<string>"
          CameraOverlayImagePath: "<string>"
          Theme: "<string>"
          ToolbarHide: "<string>"
          StartupAction: "<string>"

        GeneralSettings:
          Startup: false
          EnableWarningsElevatedApps: false
          Theme: "<string>"
          ShowNewUpdatesToastNotification: true
          AutoDownloadUpdates: false
          ShowWhatsNewAfterUpdates: true
          EnableExperimentation: false

  configurationVersion: 0.2.0