properties:
  resources:
    - resource: PowerToysConfigure
      directives:
        description: Configure PowerToys
      settings:
        PowerLauncher:
          Enabled: true
          Plugins:
            - Name: "Calculator"
              Disabled: true
            - Name: "Folder"
              Disabled: true

  configurationVersion: 0.2.0
