name: "📈 Enhance existing function"
description: Propose something better.
labels: ["Needs-Triage", "Idea-Enhancement"]
body:

- type: dropdown
  attributes:
    label: Area(s) to enhance
    description: Check all that apply.
    multiple: true
    options:
      - General
      - Always on Top
      - Awake
      - ColorPicker
      - FancyZones
      - FancyZones Editor 
      - Image Resizer
      - Installer
      - Keyboard Manager
      - Mouse Utilities
      - PowerRename
      - PowerToys Run
      - Preview Pane (Explorer)
      - Quick Accent
      - Screen ruler
      - Settings
      - Shortcut Guide
      - System tray interaction
      - TextExtractor
      - Thumbnail preview (Explorer)
      - Video Conference Mute
      - Welcome / PowerToys Tour window
  validations:
    required: true

- type: textarea
  attributes: 
    label: Description of the enhancement
    placeholder: What is the expected behavior of the proposed feature?
  validations:
    required: true

- type: textarea
  attributes:
    label: Supporting information
    placeholder: "Having additional evidence, data, tweets, blog posts, research, ... anything is extremely helpful. This information provides context to the scenario that may otherwise be lost."
  validations:
    required: false

- type: markdown
  attributes:
    value: Please limit one request per issue.
