name: "⭐ Feature request"
description: Propose something new
labels: [Needs-Triage, "Idea-New PowerToy"]

body:
  - type: checkboxes
    id: preparation
    attributes:
      label: Before filing a new issue, please check the following
      description: This makes it easier for us all :)
      options:
        - label: I am using the latest version (check for updates in Settings)
          required: true
        - label: I have searched the [online documentation](https://aka.ms/PowerToysOverview)
          required: true
        - label: I have searched in [open issues](https://github.com/microsoft/PowerToys/issues) (remember to try different search terms)
          required: true
        - label: I have searched in [closed issues](https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+is%3Aclosed) (there might be a good reason)
          required: true

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description of the new feature
      description: What is the expected behavior of the proposed feature?

  - type: textarea
    id: scenario
    validations:
      required: true
    attributes:
      label: Scenario when this would be used?
      description: What is the scenario this would be used? Why is this important to your workflow as a power user?

  - type: textarea
    validations:
      required: false
    attributes:
      label: Supporting information
      description: "Additional evidence, data, tweets, blog posts, research… Anything is helpful. This information provides context to the scenario that may otherwise be lost."

  - type: markdown
    attributes:
      value: Please limit one request per issue.
