name: "📈 Improvement request"
description: Propose an improvement for an existing feature
labels: [Needs-Triage, Idea-Enhancement]

body:
  - type: checkboxes
    id: preperation
    attributes:
      label: Before filing a new issue, please check the following
      description: This makes it easier for us all :)
      options:
        - label: I am using the latest version (check for updates in Settings)
          required: true
        - label: I have searched the [online documentation](https://aka.ms/PowerToysOverview)
          required: true
        - label: I have searched in [open issues](https://github.com/microsoft/PowerToys/issues) (remember to try different search terms)
          required: true
        - label: I have searched in [closed issues](https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+is%3Aclosed) (there might be a good reason)
          required: true

  - type: input
    id: version
    attributes:
      label: Microsoft PowerToys version
      description: Hover over system tray icon or look at Settings
      placeholder: 0.80.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes: 
      label: Description of the improvement
    validations:
      required: true

  - type: textarea
    attributes:
      label: Supporting information
      description: "Having additional evidence, data, tweets, blog posts, research... anything is helpful. This information provides context to the scenario that may otherwise be lost."
    validations:
      required: false

  - type: markdown
    attributes:
      value: Please limit one request per issue.
