parameters:
  configuration: 'Release'
  platform: ''
  additionalBuildArguments: '/p:CIBuild=false'

jobs:
- job: Build${{ parameters.platform }}${{ parameters.configuration }}
  displayName: Build ${{ parameters.platform }} ${{ parameters.configuration }}
  variables:
    BuildConfiguration: ${{ parameters.configuration }}
    BuildPlatform: ${{ parameters.platform }}
  pool: "windevbuildagents"
  timeoutInMinutes: 120
  strategy:
    maxParallel: 10
  steps:
  - template: build-powertoys-steps.yml
    parameters:
      additionalBuildArguments: ${{ parameters.additionalBuildArguments }}
