
name: .NET Core Desktop

on:
  push:
    branches: [ "test1" ]
  pull_request:
    branches: [ "test1" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    env:
      Solution_Name: PowerToys.sln
      Test_Project_Path: /src/settings-ui/Settings.UI.UnitTests/Settings.UI.UnitTests.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        architecture: x64

    - name: Execute unit tests
      run: |
        cd src/settings-ui/Settings.UI.UnitTests
        dotnet test --no-restore --verbosity:normal
