name: Submit Microsoft.PowerToys package to Windows Package Manager Community Repository 

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Specific tag name'
        required: true 
        type: string

jobs:

  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Microsoft.PowerToys
          release-tag: ${{ inputs.tag_name || github.event.release.tag_name }}
          token: ${{ secrets.PT_WINGET }}
          fork-user: crutkas
